function myFunction()
{
    var animals = [
        "Lion",
        "Tiger",
        "Bear",
        "Panther",
        "Cheetah",
        "Elephant",
        "Eagle",
        "Viper",
        "Cobra",
        "Scarpion",
        "Dragon",
        "BlackMamba",
        "Jaguar",
        "Crocodile",
        "Elephant",
        "Penguin",
        "Bee",
        "Bison",
        "Boar",
        "Buffalo",
        "Butterfly",
        "Camel",
        "Capybara",
        "Caribou",
        "Cassowary",
        "Cat",
        "Caterpillar",
        "Cattle",
        "Chamois",
        "Cheetah",
        "Chicken",
        "Chimpanzee",
        "Chinchilla",
        "Chough",
        "Clam",
        "Cobra",
        "Cockroach",
        "Cod",
        "Cormorant",
        "Coyote",
        "Crab",
        "Crane",
        "Crocodile",
        "Crow",
        "Curlew",
        "Deer",
        "Dinosaur",
        "Dog",
        "Dogfish",
        "Dolphin",
        "Dotterel",
        "Dove",
        "Dragonfly",
        "Duck",
        "Dugong",
        "Dunlin",
        "Eagle",
        "Echidna",
        "Eel",
        "Eland",
        "Elephant",
        "Elk",
        "Emu",
        "Falcon",
        "Ferret",
        "Finch",
        "Fish",
        "Flamingo",
        "Fly",
        "Fox",
        "Frog",
        "Gaur",
        "Gazelle",
        "Gerbil",
        "Giraffe",
        "Gnat",
        "Gnu",
        "Goat",
        "Goldfinch",
        "Goldfish",
        "Goose",
        "Gorilla",
        "Goshawk",
        "Grasshopper",
        "Grouse",
        "Guanaco",
        "Gull",
        "Hamster",
        "Hare",
        "Hawk",
        "Hedgehog",
        "Heron",
        "Herring",
        "Hippopotamus",
        "Hornet",
        "Horse",
        "Human",
        "Hummingbird",
        "Hyena",
        "Ibex",
        "Ibis",
        "Jackal",
        "Jaguar",
        "Jay",
        "Jellyfish",
        "Kangaroo",
        "Kingfisher",
        "Koala",
        "Kookabura",
        "Kouprey",
        "Kudu",
        "Lapwing",
        "Lark",
        "Lemur",
        "Leopard",
        "Lion",
        "Llama",
        "Lobster",
        "Locust",
        "Loris",
        "Louse",
        "Lyrebird",
        "Magpie",
        "Mallard",
        "Manatee",
        "Mandrill",
        "Mantis",
        "Marten",
        "Meerkat",
        "Mink",
        "Mole",
        "Mongoose",
        "Monkey",
        "Moose",
        "Mosquito",
        "Mouse",
        "Mule",
        "Narwhal",
        "Newt",
        "Nightingale",
        "Octopus",
        "Okapi",
        "Opossum",
        "Oryx",
        "Ostrich",
        "Otter",
        "Owl",
        "Oyster",
        "Panther",
        "Parrot",
        "Partridge",
        "Peafowl",
        "Pelican",
        "Penguin",
        "Pheasant",
        "Pig",
        "Pigeon",
        "Pony",
        "Porcupine",
        "Porpoise",
        "Quail",
        "Quelea",
        "Quetzal",
        "Rabbit",
        "Raccoon",
        "Rail",
        "Ram",
        "Rat",
        "Raven",
        "Red deer",
        "Red panda",
        "Reindeer",
        "Rhinoceros",
        "Rook",
        "Salamander",
        "Salmon",
        "Sand Dollar",
        "Sandpiper",
        "Sardine",
        "Scorpion",
        "Seahorse",
        "Seal",
        "Shark",
        "Sheep",
        "Shrew",
        "Skunk",
        "Snail",
        "Snake",
        "Sparrow",
        "Spider",
        "Spoonbill",
        "Squid",
        "Squirrel",
        "Starling",
        "Stingray",
        "Stinkbug",
        "Stork",
        "Swallow",
        "Swan",
        "Tapir",
        "Tarsier",
        "Termite",
        "Tiger",
        "Toad",
        "Trout",
        "Turkey",
        "Turtle",
        "Viper",
        "Vulture",
        "Wallaby",
        "Walrus",
        "Wasp",
        "Weasel",
        "Whale",
        "Wildcat",
        "Wolf",
        "Wolverine",
        "Wombat",
        "Ape",
        "Woodpecker",
        "Worm",
        "Wren",
        "Yak",
        "Zebra"
    ];

    var y,z;
    var str = document.getElementById("Name").value;
    var len = str.length;
    
    if (len > 0 && (str=="Krishna" || str=="krishna" || str=="Krishna Anand" || str=="Krishna anand" || str=="krishna anand"))
    {
        var x = Math.random()
        x = x * 10000;
        x = x % 16;
        z = Math.floor(x);
        document.getElementById("myPara").innerHTML = "You were a " + animals[z] + " in your previous birth";
        var btn = document.getElementById("my-btn")
        btn.hidden = "true";
    }
    else if (len > 0 && (str=="Aman" || str=="aman" || str=="Aman Kumar" || str=="Aman kumar" || str=="aman kumar"))
    {
        var x = Math.random()
        x = x * 10000;
        x = x % 16;
        z = Math.floor(x);
        document.getElementById("myPara").innerHTML = "You were a " + animals[z] + " in your previous birth";
        var btn = document.getElementById("my-btn")
        btn.hidden = "true";
    }
    else if (len > 0)
    {
        var x = Math.random()
        x = x * 10000;
        x = x % 200;
        y = Math.floor(x);
        document.getElementById("myPara").innerHTML = "You were a " + animals[y] + " in your previous birth";
        var btn = document.getElementById("my-btn")
        btn.hidden = "true";
    }

    else
    {
        document.getElementById("myPara").innerHTML = "Enter a valid name";
    }


}

function refresh()
{
    window.location.reload("Refresh")
}